create extension if not exists "pgcrypto";

create table if not exists users (
  user_id bigint generated by default as identity primary key,
  full_name text not null,
  email text unique,
  phone_number text unique,
  password text not null,
  created_at timestamptz not null default now()
);

create table if not exists emergency_contacts (
  contact_id bigint generated by default as identity primary key,
  user_id bigint not null references users(user_id) on delete cascade,
  name text not null,
  phone_number text not null,
  relationship text,
  created_at timestamptz not null default now(),
  unique (user_id, phone_number)
);

create table if not exists routes (
  route_id bigint generated by default as identity primary key,
  user_id bigint references users(user_id) on delete set null,
  distance double precision not null,
  duration double precision not null,
  safety_score double precision,
  created_at timestamptz not null default now()
);

create table if not exists locations (
  location_id bigint generated by default as identity primary key,
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  address text not null,
  created_at timestamptz not null default now()
);

create table if not exists emergency_alerts (
  alert_id bigint generated by default as identity primary key,
  user_id bigint not null references users(user_id) on delete cascade,
  timestamp timestamptz not null default now(),
  type text not null check (type in ('Medium', 'SOS')),
  status text not null check (status in ('Active', 'Resolved', 'Cancelled'))
);

create table if not exists emergency_evidence (
  evidence_id uuid primary key default gen_random_uuid(),
  alert_id bigint not null references emergency_alerts(alert_id) on delete cascade,
  type text not null check (type in ('Audio', 'Photo')),
  file_path text not null,
  timestamp timestamptz not null default now()
);

create table if not exists ratings (
  rating_id bigint generated by default as identity primary key,
  user_id bigint not null references users(user_id) on delete cascade,
  route_id bigint not null references routes(route_id) on delete cascade,
  score integer not null check (score between 1 and 5),
  comment text,
  created_at timestamptz not null default now()
);

create table if not exists safety_factors (
  factor_id bigint generated by default as identity primary key,
  location_id bigint references locations(location_id) on delete set null,
  people_density double precision check (people_density between 0.0 and 1.0),
  light_level double precision check (light_level between 0.0 and 1.0),
  risk_score double precision,
  created_at timestamptz not null default now()
);

create table if not exists incident_reports (
  incident_id text not null default ('Inc_' || substr(md5(gen_random_uuid()::text), 1, 8)),
  user_id text not null references users(user_id) on delete cascade,
  category text not null,
  description text,
  latitude double precision not null,
  longitude double precision not null,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint incident_reports_pkey primary key (incident_id)
);

create table if not exists traffic_reports (
  traffic_id text not null default ('Trf_' || substr(md5(gen_random_uuid()::text), 1, 8)),
  user_id text not null references users(user_id) on delete cascade,
  segment_id text not null,
  congestion_level integer not null check (congestion_level between 0 and 10),
  average_speed double precision,
  reported_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint traffic_reports_pkey primary key (traffic_id)
);

create table if not exists road_closures (
  closure_id text not null default ('Rcl_' || substr(md5(gen_random_uuid()::text), 1, 8)),
  user_id text not null references users(user_id) on delete cascade,
  segment_id text not null,
  reason text not null,
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  created_at timestamptz not null default now(),
  constraint road_closures_pkey primary key (closure_id)
);

create table if not exists crowd_reports (
  report_id text not null default ('Crw_' || substr(md5(gen_random_uuid()::text), 1, 8)),
  user_id text not null references users(user_id) on delete cascade,
  segment_id text not null,
  note text,
  safety_score double precision not null,
  reported_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint crowd_reports_pkey primary key (report_id)
);

create table if not exists location_shares (
  share_id text not null default ('Shr_' || substr(md5(gen_random_uuid()::text), 1, 8)),
  user_id text not null references users(user_id) on delete cascade,
  share_code text not null unique,
  is_active boolean not null default true,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  created_at timestamptz not null default now(),
  constraint location_shares_pkey primary key (share_id)
);

create table if not exists location_updates (
  update_id text not null default ('Upd_' || substr(md5(gen_random_uuid()::text), 1, 8)),
  share_id text not null references location_shares(share_id) on delete cascade,
  latitude double precision not null,
  longitude double precision not null,
  captured_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint location_updates_pkey primary key (update_id)
);
